plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
}

group = 'dev.mindsage'
version = '0.1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(
                providers.gradleProperty('javaVersion').orElse('25').get() as int
        )
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.hibernate.orm:hibernate-community-dialects'

    runtimeOnly 'org.postgresql:postgresql'
    runtimeOnly 'org.xerial:sqlite-jdbc'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
}

tasks.named('test') {
    useJUnitPlatform()
}
